🐛 ⚡ Fix comprecurse througf comp sets
goodbyekansas/nedryland pull request #313
Opened 2023-02-07 17:08 UTC by sakarias88

collectComponentsRecursive and mapComponentsRecursive ignored component-set type which was not wanted. Now it goes through those sets.

2023-02-07 17:08 UTC, sakarias88 commented
Add unit tests, fix commit message

2023-02-07 17:09 UTC, simonrainerson commented on component.nix
> +            if value.isNedrylandComponent or false || value.nedrylandType or "" == "component-set" then
Lets add some tests in `tests/component.nix`

2023-02-07 17:09 UTC, simonrainerson requested changes
Lets add some tests in `tests/component.nix`

2023-02-08 09:23 UTC, simonrainerson approved these changes

2023-02-08 09:45 UTC, simonrainerson requested changes
change change log and commit message to reflect what is going now

2023-02-08 13:28 UTC, simonrainerson approved these changes

2023-02-08 13:50 UTC, merged